// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPiZiiJ6SW2cC-dNdqiuODNUXmGnTdGk',
    appId: '1:905518005020:web:e5f35c3580dd21f864d8d9',
    messagingSenderId: '905518005020',
    projectId: 'flutter-app-fast',
    authDomain: 'flutter-app-fast.firebaseapp.com',
    storageBucket: 'flutter-app-fast.appspot.com',
    measurementId: 'G-8CW3V1E0N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUlJ9TVvlYoqTfgmZIUMnIw0JCDZEliw',
    appId: '1:905518005020:android:f485f8c01de5129064d8d9',
    messagingSenderId: '905518005020',
    projectId: 'flutter-app-fast',
    storageBucket: 'flutter-app-fast.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjagsWE2Mtf0LjNirMjBMwpjo6MGNXm6s',
    appId: '1:905518005020:ios:3f802e61f82fc52d64d8d9',
    messagingSenderId: '905518005020',
    projectId: 'flutter-app-fast',
    storageBucket: 'flutter-app-fast.appspot.com',
    iosClientId: '905518005020-vtl10h4n8ma86s360q0spv4ov9o8k416.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjagsWE2Mtf0LjNirMjBMwpjo6MGNXm6s',
    appId: '1:905518005020:ios:3f802e61f82fc52d64d8d9',
    messagingSenderId: '905518005020',
    projectId: 'flutter-app-fast',
    storageBucket: 'flutter-app-fast.appspot.com',
    iosClientId: '905518005020-vtl10h4n8ma86s360q0spv4ov9o8k416.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFast',
  );
}
